#take two numbers from the user and compare them using all comparison operators ( ==, !=, >, <, >=, <=)
a = int(input("Enter first number : "))
b = int(input("Enter second number : "))

print("a==b :",a==b)
print("a!=b :",a!=b)
print("a>b : ",a>b)
print("a<b :",a<b)
print("a>=b :",a>=b)
print("a<=b :",a<=b)